### ISSUE TITLE
ie8 if you press the cancel button on an alert you get an infinite loop

### ISSUE THREAD

**Issue by sceutre** [t4t5/sweetalert#273]
This happens for example on the samples page for sweetalerts.  The loop that is taking place is each button is continually taking focus in its handleBlur which invokes the other buttons handleBlur which takes focus ...

The issue is that IE (8 for sure, maybe 9, 10 as well) doesn't set e.relatedTarget for blur events, instead it sets e.toElement.  So the fix is simply to replace
`$focusElement = e.relatedTarget,`
with
`$focusElement = e.relatedTarget || e.toElement,`

**Comment by wizou** [comment]
Same problem here.

The solution above solves the problem with IE8 but it doesn't work with IE9 and IE10 :(

After looking the code, I think that you can remove all this piece of code (handleOnBlur) because I don't really see its usefulness :)

After several tests without this piece of code, it works fine on IE8+, Firefox, Chrome and Safari without changing the modal behavior :+1:

**Comment by sceutre** [comment]
Thanks for the heads up.  I believe the intent is it stops you from tabbing around to other (non-dialog) elements on the page.

**Comment by sabatesduran** [comment]
The solution of @wizou works for me.

**Comment by mar3les** [comment]
Had the same issue, only broken in ie8 - ie9 and 10 worked fine.
:+1: for the solution of @wizou.

**Comment by avvertix** [comment]
The solution worked on IE8, but on IE10 and IE11 the page will get somehow unresponsive.

I've found that `$focusElement` could be `undefined` and adding a check for that state seemed to work for me

**Comment by t4t5** [comment]
Support for IE8 is no longer actively maintained.
