### ISSUE TITLE
input fields all set to display:none.

### ISSUE THREAD

**Issue by PommeVerte** [t4t5/sweetalert#331]
Hey guys,

I've found that when using `html: true` we can **not** include any input fields or they will be hidden by `sweetalert.css > input{display:none}`.

Sometimes it's interesting to load our own forms within the alert and this is blocking that atm. 
A fix for this would be to give the HTML input element a class and apply the input styling to that class rather than all inputs.

I'm willing to make a pull request if someone can validate this from a functional perspective.

**Comment by samhavens** [comment]
@PommeVerte ,

The line of CSS you mention is in there, however, if you wrap your input in form tags, and have styling like `form input {display:block}` that should take precedence.

There is another problem putting form fields in using `html: true`, because everything in `text` gets wrapped in `<p>...</p>`, and it is invalid to have form elements inside `p` tags. I fixed this locally by switching the `p` tags for divs. I will fork and submit a pull request; you are welcome to checkout my fork.

**Comment by Mart-Bogdan** [comment]
That's quite not an issue, you can always override that with CSS, I'd close this Issue.

**Comment by t4t5** [comment]
In SweetAlert 2.0, each modal is rendered from scratch instead of showing/hiding inputs, so this should work now!
