### ISSUE TITLE
Why you doing this to me!?

### ISSUE THREAD

**Issue by mateuszjarzewski** [t4t5/sweetalert#333]
Please, stop changing files path, it's breaking my stuff!
Few days ago this link was perfectly fine:
http://rawgit.com/t4t5/sweetalert/master/lib/sweet-alert.min.js
Now it's broken becouse of your pointless moves.

Thank you.

**Comment by t4t5** [comment]
If you're using SweetAlert in an app, you really shouldn't link to a URL that you have absolutely no control over. Instead, download the files with Bower or NPM, or link to a CDN which uses version numbers.

Since this is 1.0.0 though, you'll be happy to know that the file structure won't change again. But please change the way you link to external files, it's destined to go bad!

**Comment by mateuszjarzewski** [comment]
I know what i'm doing. There is no time to lose when building simple, couple hundreds line app.

**Comment by t4t5** [comment]
Both the README and the project site clearly state what the best practice is for using this library. If you choose to ignore that because you have "no time to lose", then that's your problem.

**Comment by chriscct7** [comment]
@mateuszjarewaski clearly you had no idea what you are doing because you'd know that rawgit.com is in no way affiliated with GitHub
