### ISSUE TITLE
[Feature Request] Customize class buttons

### ISSUE THREAD

**Issue by marcemira** [t4t5/sweetalert#413]
Is there a chance to be able to add class to confirm / cancel buttons? also disable inline styles. 
Something like this: 

```
  confirmButtonText: 'OK',
  confirmButtonColor: '#8CD4F5',
  confirmButtonClass: ' ',
  cancelButtonText: 'Cancel',
  cancelButtonColor: '#D0D0D0',
  cancelButtonClass: ' ',
  unstyleButtons: false,
```

Thanks!

**Comment by adrian-e** [comment]
+1, specially for removing inline styling (should use classes)

**Comment by pbassut** [comment]
+1

**Comment by anatolibarski** [comment]
Pleeeeeeasse remove the inline styles!! I think it's a major issue everybody needs to restyle sweetalert who is using it seriously.

I'm using sass & bootstrap, so I would only need something like this:

.sweet-alert button.confirm {
    @extend .btn-primary;
}
.sweet-alert button.confirm {
    @extend .btn-default;
}

instead of copying pages of css code from bootstrap and setting !important everywhere (which is an easy-to-avoid anti-pattern) to do the same.

**Comment by Charlex** [comment]
+1

**Comment by jonathanhills** [comment]
+1

**Comment by Stiropor** [comment]
+1
Shame this is ignored, it's a deal breaker, I cannot use this - editing styles on two places is bad idea, not to even mention inline styles.

**Comment by ClemRz** [comment]
+1

**Comment by t4t5** [comment]
Inline styles have been removed in SweetAlert 2.0. You can also add you own classes using the new [button options](https://sweetalert.js.org/docs/#button). For more info, check out the [upgrade guide](https://sweetalert.js.org/guides/#upgrading-from-1x)
