### ISSUE TITLE
Modal open/close fade animation

### ISSUE THREAD

**Issue by ddd111ddd** [t4t5/sweetalert#435]
My current setup:

```
sweetAlert.setDefaults({
    animation: false
});
```

When the swal modal opens or closes I still get a "fade" effect. It's especially noticeable on low spec mobile phones as the overlay appears after the sweet-alert div.

I solved by using:

```
.sweet-overlay {
    opacity: 1 !important;
}
```

Shouldn't that be considered an animation too?

Anyway, just a suggestion and future reference for people with the same problem. Unfortunately even high-end phones struggle to deliver fade effects (GPU accelerated or not). Maybe it's the overflow-y who actually causes the animation delay on pages with big DOM trees, but I'm far from a front-end expert.

**Comment by andreialecu** [comment]
I noticed this too, the problem is that the fading is done via javascript instead of CSS transitions.

Relevant code:
https://github.com/t4t5/sweetalert/blob/249e728a8e66190c3b55363f097af1f300cb273c/dev/modules/handle-dom.js#L83

This should be refactored to use CSS transitions, it would make it much smoother.

**Comment by t4t5** [comment]
SweetAlert 2.0 now only uses CSS animations. Check out the [upgrade guide](https://sweetalert.js.org/guides/#upgrading-from-1x)!
