### ISSUE TITLE
Bug on cancel callback when binding

### ISSUE THREAD

**Issue by luisgarciaalanis** [t4t5/sweetalert#480]
swal({
                title: title,
                text: message,
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: okButtonText,
                closeOnConfirm: true,
                closeOnCancel: true
            },
            proceedCallback.bind(this) <------- THIS triggers the bug, the callback is not called on cancel
        );

proceedCallback(isConfirm) {....}

Its because of the way you check for parameters, seems like bind adds another one

**Comment by moore0n** [comment]
The issue is in this code.
  // Check if callback function expects a parameter (to track cancel actions)
  var functionAsStr = String(params.doneFunction).replace(/\s/g, '');
  var functionHandlesCancel = functionAsStr.substring(0, 9) === 'function(' && functionAsStr.substring(9, 10) !== ')';

When you bind a function it returns a new instance of a function, which doesn't explicitly specify a param.

example : 
String(window.alert.bind(this, 'test'))
"function () { [native code] }"

// Straight function declaration
String(function(test){});
"function (test){}"

It appears that they are trying to only fire the handler if the function passed as the callback specifies the incoming property for isConfirm.  This seems like a bit of bad practice. The callback should always fire if its specified, it should be up to the user to check that value to ensure it was confirmed.

**Comment by moore0n** [comment]
A work around of course would be to use the var _this = this method. But bind should be supported in this case.

**Comment by t4t5** [comment]
The latest release no longer checks for callbacks in the old hacky way, but uses [promises](https://sweetalert.js.org/guides/#using-promises). :)
