### ISSUE TITLE
Old prompt is modal but how about sweet alert?

### ISSUE THREAD

**Issue by funchiat** [t4t5/sweetalert#518]
I am trying to get user remarks before submit to server. I must trigger this remark when user clicks button. Here's where I use sweet alert replacement for windows.prompt but it's not modal in my code. I trigger sweet alert code in OnClientClick. There will be a hidden field ready. And OnClick suppose to run at server side with access to hidden field. 

But before all this, here's my problem: sweet alert in OnClientClick is not modal and broken. It flows automatically to OnClick. The prompt did appear, for 1 second. What did I miss and what are my options?

   function getApproverRemarks() {
       return swal({
           title: "An input!",
           text: "Write something interesting:",
           type: "input",
           showCancelButton: true,
           closeOnConfirm: false,
           animation: "slide-from-top",
           inputPlaceholder: "Write something"
       }, function(inputValue) {
           if (inputValue === false) return false;
           if (inputValue === "") {
               swal.showInputError("You need to write something!");
               return false
           }
           swal("Nice!", "You wrote: " + inputValue, "success");
       });

   }

```
        <ItemTemplate>

        <asp:LinkButton ID="lbApprove" runat="server" 
            Text='<%#  (DataBinder.Eval(Container.DataItem,"IsApprovalAccepted").ToString() == "True" ) ? TextToNoLongerApprove : TextToNowApprove  %>'
            CommandArgument='<%# Bind("ProjekId") %>' OnClientClick="return getApproverRemarks();" OnClick="lbApprove_Click"/>
        </ItemTemplate>
```

**Comment by justin-oj-orange** [comment]
There is no way for SweetAlert to emulate genuine Modal Behavior. The default modal dialogs in the Browser (i.e. alert(), confirm() and prompt()) all block, waiting for user involvement. There is no way in JavaScript to write blocking code, and SweetAlert doesn't try to (because it can't). You need to change your approach.  From the OnClientClick point of view, you are returning the value from swal. swal just returns undefined. So essence you OnClientClick handler is immediately being told return undefined, which does nothing and the linkbutton quite happily continues calling the link, and then hitting the OnClick server side. Sweet alert starts to show but because the code has not been stopped, it will quite happily continue calling the server and refreshing the page. You have to stop the code immediately, then let sweet alert display and get the data you want, and then you need to write code to continue. 

In your code the callback is the anonymous function (function(inputvalue)) and the inputvalue parameter is the value the user put in the input box (or false if they clicked cancel). 

something more like:
`function getApproverRemarks() {
   swal({
        title: "An input!",
        text: "Write something interesting:",
        type: "input",
        showCancelButton: true,
        closeOnConfirm: false,
        animation: "slide-from-top",
        inputPlaceholder: "Write something"
    }, function (inputValue) {
        if (inputValue === false) return false;
        if (inputValue === "") {
            swal.showInputError("You need to write something!");
            return false
        }        
        //At this point you have a valid input value
        //As to where you want to put the InputValue -- unsure?
        //You mentioned a hidden field?
        document.getElementById('hiddenfieldid').value = inputValue;
        //Now you will need to continue to the Server Side OnClick Event
        //Which will entail emulating exactly what the control would have done in a normal course of events
        //usually something like....
        __doPostBack('<%= lbApprove.UniqueID %>', '');
        //Although becuase it appears this LinkButton is actually in a repeater, this may not work
        //and it could be difficult to emulate exactly the 'default' behaviour espacially since you also have a CommandArgument
        //But this would be some of the joy with ASP.NET WebForms
    });
   return false; //This returns immeditaely to the OnClickClick function stopping it
}`
