### ISSUE TITLE
form in alert

### ISSUE THREAD

**Issue by antonioaltamura** [t4t5/sweetalert#530]
Hi, I really appreciate your plugin, it's even too simple.
what's do you think is the best way for show a form in the alert, and combine this with an ajax request as callback, obiouvsly with the form data?

**Comment by lancedouglas1** [comment]
Look at [swal-forms](https://github.com/taromero/swal-forms).  Works as an excellent extension to swal.

**Comment by sunilsmith** [comment]
It works great but I need to include a calendar or date-picker within the form. If it's not possible as an alternative I was thinking to bind a HTML page within sweet alert. so that when my sweet alert triggered it should show the html page in its body. can you please give a suggestion to both the queries.

**Comment by t4t5** [comment]
This project isn't going to support setting custom HTML as strings, as I think it reinforces bad design patterns. If you want a custom modal, it should be built from scratch or using another library. SweetAlert just aims at providing a better version of `alert` with some extra features, NOT replace all your modals. :)

**Comment by sunilsmith** [comment]
Thanks @t4t5 i understood your point and @lancedouglas1 thanks for your swal-form link ...
