### ISSUE TITLE
HTML content won't allow `input` elements

### ISSUE THREAD

**Issue by alvarotrigo** [t4t5/sweetalert#540]
When trying to add a checkbox to the modal, it seems to be totally ignored. 
The same happens with any other input element.

[Reproduction online](https://jsfiddle.net/wwzbeL95/)
[Reproduction online (with `type: 'input'`)](https://jsfiddle.net/wwzbeL95/1/) (gets transformed into a text input)

[Reported in stackoverflow as well](http://stackoverflow.com/questions/30655649/sweet-alert-with-form-js-3-input)

**Comment by nodeman777** [comment]
+1

**Comment by HannesOberreiter** [comment]
+1 yes, it is because sweet alert css hides all input fields. When you don't use the build-in input field. My workaround is to simply show my custom input field with jquery selector. 

Best would be if the build-in sweet alert gets a custom class name and id. 

`
.sweet-alert input {
....
 display: none;
....
}
`

Cheers
Hannes

**Comment by t4t5** [comment]
This project isn't going to support setting custom HTML as strings, as I think it reinforces bad design patterns. If you want a custom modal, it should be built from scratch or using another library. SweetAlert just aims at providing a better version of `alert` with some extra features, NOT replace all your modals. :)
