### ISSUE TITLE
Read this first - Use sweetalert2

### ISSUE THREAD

**Issue by diego-vieira** [t4t5/sweetalert#571]
This project seems to be dead and a new fork is up - https://github.com/limonte/sweetalert2

**Comment by Eric1084** [comment]
I'm having the exact same problem on the fork too.
https://github.com/t4t5/sweetalert/issues/576

**Comment by t4t5** [comment]
@diego-vieira Sorry, the project isn't dead. I just haven't had time to go through pull requests and issues lately.

sweetalert2 was forked before v1.0, so the structure of the project is quite different. This doesn't necessarily mean that it's not a good alternative. If there's a feature in there that you need, you should of course use it.

It kinda bugs med that it's called sweetalert2 though, since that makes it sound like it's a natural progression of this project, even though I'm planning a 2.0 release later this year...

Anyways, free software, do what you like. Just wanted to say sorry for being unresponsive, and that I'm planning on becoming more active soon.

If there are any good candidates to help med maintain the project, please let me know!

**Comment by diego-vieira** [comment]
hello @t4t5 thank you so much for getting back to us and my apologies for saying that. Open source is both a gift and a curse, that's why collaborators are here for.

I know that sometimes we need to focus on something else and it's always a good choice to invite collaborators.

Cheers
