### ISSUE TITLE
SweetAlert does not behave like the browser alert

### ISSUE THREAD

**Issue by luanfonceca** [t4t5/sweetalert#644]
Hi folks, i was using the default browser confirmation alert in the `update` event to confirm if the users really wants to change the order. And its was working because i think that the browser locks the execution of the ui-sortable, but now i am using the [sweetAlert](https://github.com/t4t5/sweetalert) and its not working anymore.

You all can see in this two links:
Using the browser alert: http://recordit.co/FlIUmVxk7X
Using the sweetAlert: http://recordit.co/3jdbDgozx3

As you can see in the browser alert the execution was stopped as soon as the alert shows up, but thats not happen with the sweetAlert. I think that if there is another way to get the confirmation, by not using a callback function it should work nicely.

Thanks in advance and i hope if it is all well explained.

**Comment by siewers** [comment]
AFAIK there is no way to break the script execution with any JavaScript code. The alert is something the browser natively handles and breaks the execution internally.
Since SweetAlert is a script running in the browser just like your own, you will have to design your code so the callback from SweetAlert is triggering your sorting.

**Comment by t4t5** [comment]
Indeed, it's impossible to fully reproduce this behaviour.

The closest thing today would be to use `await swal()` in SweetAlert 2.0 to prevent the next lines from executing.
