### ISSUE TITLE
How to handle cancel button action

### ISSUE THREAD

**Issue by Zorgatone** [t4t5/sweetalert#656]
We have a callback parameter for the confirm button, but how can we use a callback for the cancel button?

**Comment by Zorgatone** [comment]
I see in the code there's a `doneFunction` parameter.

I'm trying this code but seems my callback is ignored completely, what am I doing wrong?

```JavaScript
new Promise((resolve, reject) => {
  swal({
    title: "Eliminare banner?",
    text: "I dati eliminati andranno persi.",
    type: "warning",
    showCancelButton: true,
    confirmButtonColor: "#DD6B55",
    confirmButtonText: "Elimina",
    closeOnConfirm: false,
    html: false,
    doneFunction(res) {
      if (res) {
        resolve();
      } else {
        reject();
      }
    }
  });
});
```

**Comment by jeffmath** [comment]
Same thing for me.  My callback function is called when the ok button is clicked, but not for the cancel button.

**Comment by Zorgatone** [comment]
@jeffmath I switched to https://github.com/limonte/sweetalert2 to solve that

**Comment by t4t5** [comment]
You can find an example of how to do this in the documentation: http://t4t5.github.io/sweetalert/

"... and by passing a parameter, you can execute something else for 'Cancel'."

```js
swal({
  title: "Are you sure?",
  text: "You will not be able to recover this imaginary file!",
  type: "warning",
  showCancelButton: true,
  confirmButtonColor: "#DD6B55",
  confirmButtonText: "Yes, delete it!",
  cancelButtonText: "No, cancel plx!",
  closeOnConfirm: false,
  closeOnCancel: false
},
function(isConfirm){
  if (isConfirm) {
    swal("Deleted!", "Your imaginary file has been deleted.", "success");
  } else {
    swal("Cancelled", "Your imaginary file is safe :)", "error");
  }
});
```

**Comment by arpit786shukla** [comment]
@t4t5 Through isConfirm, we can check if the user response was Confirm button or something else. But could you please tell me how to check if the clicked button was a "Confirm" button or "Cancel" button or "Close" button because I'm using Cancel button also to redirect somewhere else but close button just closes the alert?

**Comment by gualopezb** [comment]
The actual issue is that in sweetalert v1.x the cancel handler is checking for the callback starts with `function(` https://github.com/t4t5/sweetalert/blob/v1.1.3/lib/modules/handle-click.js#L119.
So if that condition is not met, as @Zorgatone's example is using `doneFunction(` the callback is just going to be ignored.

**Comment by jdurand** [comment]
Good catch @gualopezb. I've had this working forever and it suddenly stopped working.

Le fix:
 
```diff
-    }, (code) => {
+    }, function(code) {
```

I'm guessing some change in my Babel configuration is at play.
