### ISSUE TITLE
Content does only work for Form Element Nodes?

### ISSUE THREAD

**Issue by HannesOberreiter** [t4t5/sweetalert#713]
Hi,

thanks for the new update works good so far.

Seems like the content option only works for form type fields, dont know if this was intended.

Here a small fiddle with p element:
https://jsfiddle.net/1ogbtxfx/1/

Cheers
Hannes

**Comment by t4t5** [comment]
I took a closer look and it seems like it does actually render, but it's invisible because the p-tag inherits from `.swal-overlay` (which uses `font-size: 0` for alignment reasons).

This should definitely be fixed for the next release! It can easily be done by specifying `font-size: initial` in the CSS for `.swal-content`!

**Comment by HannesOberreiter** [comment]
Thanks, sorry I did not look closer into it myself.

Cheers
Hannes
