### ISSUE TITLE
Text doesn't style.

### ISSUE THREAD

**Issue by eddiejibson** [t4t5/sweetalert#718]
Hi,

So, I added `<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>` to the head of my html page, so I could test out Sweetalert 2, wondering why there was no longer a cdn for the css, either, which I was hoping there would be as I tend to not like using libraries. And, basically, text didn't style as it should. See image to explain what I'm talking about [here](https://imgur.com/a/FEB0O). Any chance you could bring the old cdn style back, too? Or, suggest how else I could do this without a library.

Thanks.

**Comment by t4t5** [comment]
Hey Eddie,

SweetAlert 2 no longer has a separate .css-file because the CSS automatically gets injected through the JS-file now instead! One file to rule them all = less to worry about. :)

The font-styling has deliberately been removed because I think the `font-family` property should be inherited from whatever the web app is using instead to give it a more consistent UI.

You can easily set the font just by styling your body tag:

```css
body {
  font-family: Helvetica;
}
```

...or if you want to only target the modal:

```css
.swal-modal {
  font-family: Helvetica;
}
```

Cheers!
