### ISSUE TITLE
How to include sweetalert.min.js in file

### ISSUE THREAD

**Issue by vinothrajm** [t4t5/sweetalert#721]
Hi,
Im using angular 1.5
The older version of sweet alert folder structure differs from the current version.
In older version, i have included the sweetalert.min.js file as follow,
<script src="../bower_components/sweetalert/dist/sweetalert.min.js"></script>

But in the current version dist folder is not available.

So, can you please tell me which file in need to include to use sweetalert.

**Comment by t4t5** [comment]
Since [Bower is being deprecated](https://github.com/bower/bower/issues/2298) I'd encourage users to use workflow consisting of NPM + a module bundler like Webpack instead.

That being said, you can still use SweetAlert with the good 'ol 1998 script tag. Just change it to:

```html
<script src="../node_modules/sweetalert/dist/sweetalert.min.js"></script>
```

...after downloading SweetAlert with `npm install sweetalert --save`.

**Comment by michaelsogos** [comment]
@t4t5 
If i can say, i not agree with the above answer.

Not every project use packer like webpack or browserify, and also pure web project should not use (and should not be recommended) to use NPM because those packages are built with NODEJS in mind and not BROWSER.

Again i not agree with suggesting to use "1998 script tag", because modern application use a kind of lazy JS loader (like require.js or others), and for pure SPA application (no matter which back-end) is very important to have a distributable file.

Can you consider to re-introduce DIST folder, because i guess that force developer to add a WORKFLOW like with WebPack is a too much opinionated solution.

**Comment by t4t5** [comment]
@michaelsogos NPM is *not* just for server-side NodeJS, but [also for client-side JavaScript](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging). Even Bower themselves [recommend using it](https://bower.io) instead of their own package manager nowadays.

And I think you've misunderstood. There's still a `dist` folder, it's just not commited to GitHub anymore (because it shouldn't be). But if you run `npm install sweetalert` you'll see the `dist` folder there. :)

**Comment by michaelsogos** [comment]
@t4t5 NPM is not just for nodejs, it is true, but also 60% of code wrote and packaged with NPM use latest javascript standards ( i mean ES6 and above) and this is the first reason why bower exist, to maintain library fully compatible with browser.

Also i was looking for DIST folder in bower package that not exist at least on 2.0.3 package version, i know it exist in NPM😀.

However we are evaluating also yarn packages.
