### ISSUE TITLE
SweetAlert vs SweetAlert2

### ISSUE THREAD

**Issue by Fatih90** [t4t5/sweetalert#726]
im not sure if i should use this package instead of [SweetAlert2](https://github.com/limonte/sweetalert2)

it looks like [SweetAlert2](https://github.com/limonte/sweetalert2) is updated more often than this one

what do you people think ?

**Comment by t4t5** [comment]
As the author of the library I'm obviously a little biased, but here's my take on it.

SweetAlert2 is a fork of the original SweetAlert pre-1.0 code. It was forked due to the fact that this original library was updated quite infrequently in the past.

Since then, SweetAlert 2.0, the next version of the "real" SweetAlert (yes, it's confusing) has been released though, and I think it addresses most, if not all of the issue people had with the original library and more.

Personally, I'm not very fond of the fork, since I think it bloats the library with far too many random, unpolished features. I also think the name "SweetAlert2" is a bit misleading, but since this is open-source, people are free to choose whatever they prefer. :)

My suggestion is to go through the features of both projects:
SweetAlert: https://sweetalert.js.org
SweetAlert2: https://limonte.github.io/sweetalert2

...and see which one suits your project best.

**Comment by taxpayer** [comment]
I found out the SweetAlert project in the very beginning. It's pretty obvious that @t4t5 is a gifted designer, you just need to visit Swal's website (old and current one) and his other sites to realize that. BTW, that's why the first Swal took so much my attention, is is simply beautiful.

But unfortunately the original project was "abandoned" for a long period and those ones, including me, who were using Swal in their projects saw in @limonte's fork, SweetAlert2, an alternative to the bugs and desired new features that were not being implemented in the original one.

Today I'm a user of Swal2 for a long time and it's pretty clear that @limonte has made a wonderful job keeping up the project and improving it. Today I consider it another project, apart from Swal. 

The "perfect scenario", IMHO, was if Swal could be only one project and all the PR's and bug reports could be fixed in the past, but things did not happed that way. So, today, we have 2 completey different projects and I think that the best way to make a decision is really compare both and choose one.

I had to write this because I thank @t4t5 for his incredible original idea, but I also have to thank big @limonte for his hard work all over the years to make the original idea possible to use.

**Comment by Fatih90** [comment]
@t4t5 and @taxpayer Thanks for the comments, because i use sass in my project i will go for [SweetAlert2](https://github.com/limonte/sweetalert2) because it's using sass. i will use the original sweetalert until you support sass :)

**Comment by t4t5** [comment]
@Fatih90 I'm not sure what you mean when you say that "it supports sass", since it all gets compiled to CSS anyway. You can use both SweetAlert and SweetAlert2 regardless of what preprocess or you use. :)

**Comment by limonte** [comment]
> SweetAlert2: https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/
