### ISSUE TITLE
sweetalert.min.js?

### ISSUE THREAD

**Issue by jamiesonbecker** [t4t5/sweetalert#733]
Hi Tristan,

awesome job revitalizing sweetalert!! Super excited that it's seeing some serious love, and the new site looks awesome. Do you have the minified version somewhere on the site or github repo, or is this the only one?

https://sweetalert.js.org/assets/sweetalert/sweetalert.min.js

It's a lot quicker for me to do wget someurl and I don't use npm in my workflow. ;)

Thanks and really stoked about SA all over again!

**Comment by t4t5** [comment]
Hi @jamiesonbecker, thanks for the kind words!

The `dist` folder is no longer commited to the GitHub repo, since build files should be kept out of source-control. 

You can however still find them on CDNs like unpkg: https://unpkg.com/sweetalert/dist/sweetalert.min.js

**Comment by jamiesonbecker** [comment]
Understand your logic on build artifacts, although a lot of JS projects still provide their dist/. Is it feasible to add a direct link to `sweetalert.min.js` on your docs or main page? This might help people who have their own build system or for some reason eschew the One True Way(tm) ;-)

**Comment by t4t5** [comment]
There are already links to unpkg and jsDelivr in the [guide on the official page](https://sweetalert.js.org/guides/#cdn). I think that's enough :)

**Comment by daftspunk** [comment]
Need unminified compiled source file. This URL is doesn't appear to work work: https://unpkg.com/sweetalert@2.0.6/dist/sweetalert.js

 Browserify or Webpack is a requirement to use this project? Yikes!

**Comment by jamiesonbecker** [comment]
@daftspunk agreed!!

Once I understood it (the docs are a little weak in this area), I actually thought the content concept in this project was pretty interesting and much more flexible/powerful than either the original or https://limonte.github.io/sweetalert2/

However, I switched back on the original sweetalert so that I don't have to rewrite every single use in my project (dozens of different dialogs for things from deleting something to logging out confirmation).

(Heads up to others: neither this rewrite of the original version nor sweetalert 2 are backwards-compatible with the original, and it looks impossible to track down any original unminified versions of sweetalert 1, but minified versions are available here: https://cdnjs.com/libraries/sweetalert .)

There are still some small bugs in this version that'll probably keep me off of it unfortunately, even if it was backwards-compatible with the original. The biggest blocker right off the bat was the total lack of support/interest for just dropping the file into my source repo and using it. I don't quite understand the effort in building such a beautiful piece of code and website, but then not encouraging its wide-spread usage. Maybe @t4t5 prefers it to be admired, but not used. ;)

**Comment by daftspunk** [comment]
I think you said it best with:

> the One True Way(tm)

This project is a fine example of modern web development, very impressive. It is a little too ahead of its time for me, I have been developing websites for almost 20 years, with a fully developed [process and platform](https://github.com/octobercms/october)--that even uses an [older version of SA](https://github.com/octobercms/october/blob/master/modules/backend/assets/vendor/sweet-alert/sweet-alert.js). In this latest SA repo the build is still young, hopefully we can push our case that accessibility matters when paying respect to the past ways.

**Comment by t4t5** [comment]
I think I need to clear some points up.

Using Browserify or Webpack is certainly *not* a requirement to use this library – just a good practice for using dependencies in a sane way. 

As I pointed out, you can also very easily link directly to the minified source file (available on CDNs like unpkg or jsDelivr), *or* you can `npm install` SweetAlert in your project and import the minified source from your local folder. Nothing's really changed, apart from the fact that distribution files aren't commited to the GitHub repo (since they shouldn't) and that Bower has been deprecated (for a good reason).

I personally think it's good for library authors to encourage new best practices when it comes to web programming. The web (and JavaScript in particular) is changing rapidly right now – imo we should embrace the new and abandon the old, so that we can all become better developers in the process.

An example to illustrate why I think this is important: SweetAlert 1.X used to have an `html` option where you could pass HTML strings that would get parsed and shown in the modal. The idea was that you should be able to easily format text like this:

```javascript
swal({
  html: "<b>Stop!</b> Are you sure you want to do this?",
})
```

However, what I noticed was that people were quickly abusing this functionality in absurd ways. Many started putting whole forms and web pages in that `html` option, just because they needed a modal interface around it. As you probably know, editing complex HTML as a long string of text is a really bad practice, creating code that's not only hard to maintain, but also opens up for dirty injection attacks. 

Libraries should always discourage bad practices. That's why I removed the `html` option altogether in 2.0 and replaced it with the much cleaner `content` feature. Annoying for some, yes – but I wouldn't want to work on a library that encourages bad code.

Out of curiosity @jamiesonbecker, what are the "small bugs" that keep you from upgrading at the moment?

**Comment by jamiesonbecker** [comment]
@t4t5 I do understand your point of view, but it seems overly prescriptive to me and illustrates that you seem to believe that you have a "best" practice that's better than others of us. (For example, I've been coding HTML since around 1994.) Just because we might have a different perspective doesn't mean our thoughts don't matter. (fwiw, I began my career at IBM, where we went to legendary heights to maintain backwards compatibility even for products that were decades old.)

I specialize in secure code and do agree that the html option could result in XSS, and I also happen to believe that your replacement of html with content was truly a huge improvement -- but removing html means that you broke backwards compatibility and necessitates a code rewrite across the board; worse yet, because your old sweetalert and new sweetalert code are not compatible with each other, I can't simple add a wrapper and gradually upgrade; it's an all or nothing approach, which means that I've opted for *nothing*. To simply leave html in there but mark it as deprecated would have been the preferred approach, to my view.

Sometimes the pursuit of 'best' practices often results in results that are suboptimal. For example, there are many reasons why @daftspunk might need access to the unminified source (perhaps for audit purposes, or for open source review with external teams) that means going through the whole compile process might negate its utility.

I know you're not getting paid for any of this, and open source communities are often a thankless place, so I just want to add: thank you! you've done a great service to the community by writing both the original sweet alert, and this new (and greatly improved) version. We might disagree on some fundamentals, but do appreciate you hearing out countervailing viewpoints. Other things, like Manchester United FC, are clearly of much greater urgency. ;)

(by the way, the bug report that would have necessitated writing a wrapper method and global s&r that I ended up rolling back instead of committing to move forward on this: https://github.com/t4t5/sweetalert/issues/735 ; this is a minor regression, to me; the loss or change of nearly every function param in this new version was enough of a showstopper that I had to yank out our partial migration in favor of just sticking with the old version)

**Comment by daftspunk** [comment]
Having never encountered an exclusive policy like this, I'm truly lost for
words.

**Comment by daftspunk** [comment]
I am fine with this projects breaking changes, I am fine with the versioning, I'm fine with your build system--I just cannot use it. Please heed this requirement from an average joe: **I need unminified source files so I can prove they are not malicious**.

Your project already builds the documentation, I don't see what is the big deal.

**Comment by t4t5** [comment]
Seems like we are talking about two different issues here, so I'll address your concerns in #748 instead @daftspunk.

**Comment by jamiesonbecker** [comment]
@t4t5 agreed! Maybe even three:

1) the virtues vs tradeoffs of maintaining backwards compatibility with previous versions
2) code distribution practices that only work with new npm-centric tools vs the purity of maintaining a repo clean of build artifacts vs dropping the .js and .min.js in a github release binary download page.
3) perhaps, trusting your users to not shoot themselves in the foot (again). ;)

**Comment by daftspunk** [comment]
Yes, my apologies, I realise that I was imposing my solutions (add the dist/ folder back) when I should have been [stating my problem instead](http://xyproblem.info/).
