### ISSUE TITLE
Content <select> add <option>'s

### ISSUE THREAD

**Issue by SanyBoK** [t4t5/sweetalert#751]
Well, tried to add options to select in content. Any advise how to do it? Thanks.

```javascript
content: {
   element: "select",
   attributes: {
         className: "select2"
   },
   ???
}
```

**Comment by t4t5** [comment]
Since this is not just a single element, you'd need to pass the whole tree of elements to SweetAlert's `element` attribute. This is how you would create the following markup:

```html
<select>
  <option>Option 1</option>
</select>
```

...in pure JS:

```javascript
const select = document.createElement("select");
const option = document.createElement("option");
option.textContent = "Option 1";
select.appendChild(option);
```

As you can see, it's pretty tedious though, so I recommend using a UI framework like React to create more advanced DOM content.

You can also keep an eye on [this plugin](https://github.com/sweetalert/sweetalert-react) that I'm working on to make this type of behaviour easier to implement. Although keep in mind that it hasn't officially been released yet.

**Comment by eraporsmk** [comment]
how can get selected value?
