### ISSUE TITLE
Nodejs sweetalert redirect before user click OK 

### ISSUE THREAD

**Issue by Pranjali30Soni** [t4t5/sweetalert#779]
after form submission the alert should be shown. window.alert works fine but sweetalert doesn't wait to get clicked. It comes and disappear within a second. I'm creating a desktop application using nodejs and electron.

**Comment by girishpatil** [comment]
I think you are not preventing the form submission event. The very window.alert works differently and the sweetalerts popups work differently.
The window.alert() when  called stopd the further execution until response from alert box. But sweetalert runs a chunk of code although it can wait for things to be completed (Promises) but sweetalert(not just sweetalert any chunk of code) doesn't stop if you dont prevent explicitly by calling `event.preventDefault()`. You can later redirect/submit when needed. 

Please do share that part of your code, so that I can know more about it.
Hope this helps

**Comment by lionralfs** [comment]
Hey @Pranjali30Soni,
I've made a quick example to illustrate what @girishpatil explained above: https://codepen.io/lionralfs/pen/xWEqaE?editors=1010
