### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of null 

### ISSUE THREAD

**Issue by BernhardBehrendt** [t4t5/sweetalert#78]
I run into problems if I try to get the example working to initially setup sweetalert.
Problem occurs in various Browsers (Chrome latest, Firefox latest)

Executing following code produces an error:

```
$(document).ready(function () {
    swal({title: 'Error!', text: 'Here\'s my error message!', type: 'error', confirmButtonText: 'Cool'});
});
```

Error -> `Uncaught TypeError: Cannot read property 'querySelector' of null`

After modifying the demoscript to following example it's working fine:

```
$(document).ready(function () {
    setTimeout(function () {
        swal({title: 'Error!', text: 'Here\'s my error message!', type: 'error', confirmButtonText: 'Cool'});
    }, 1000);
});
```

**Comment by yalmasri** [comment]
try running 'sweetAlertInitialize()' before running 'swal'

**Comment by bartvanderwal** [comment]
I had this same error. version 1.0.1 (or so the package.json says). I was refactoring sweetAlert to an Angular service for reuse.

For me the issue was solved by just wrapping the `swal` call in a function:
function() {
   swal();
}

Something to do with the scope of `this` I think. I guess this is a similar solution as wrapping it in a `setTimeout()` as @BernhardBezdek dus. Except that that also puts calling the function at the end of the queue. But at least in my case it wasn't an asynchronous issue.

Luckily Ecmascript 6 solved this weird Javascript behaviour with `this`. Now to wait until all browsers support it (or setup that polyfill/transpilation environment).

**Comment by GustavoDesc** [comment]
-------------------Android Studio--------
D/CordovaWebViewImpl: onPageFinished(file:///android_asset/www/outra_pagina.html?id_titulo=1)
D/SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 43 : Uncaught TypeError: Cannot read property 'querySelector' of null
I/chromium: [INFO:CONSOLE(43)] "Uncaught TypeError: Cannot read property 'querySelector' of null", source: file:///android_asset/www/js/index.js (43)
D/SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 43 : Uncaught TypeError: Cannot read property 'querySelector' of null
I/chromium: [INFO:CONSOLE(43)] "Uncaught TypeError: Cannot read property 'querySelector' of null", source: file:///android_asset/www/js/index.js (43)
