### ISSUE TITLE
criate minifide code

### ISSUE THREAD

**Issue by boanneu** [t4t5/sweetalert#784]
if a try to minifide my code

it will falle on ::

.then(somtingHere => { }

how can i fix this ?

**Comment by lionralfs** [comment]
Hey @boanneu 

I'm guessing this is rather an issue with the minifier not being able to understand ES6 arrow functions instead of the library itself. Try to either
- Change ` .then(somethingHere => { }` to `.then(function(somethingHere) { }`
- Or use a transpiler like [babel](https://github.com/babel/babel) to transform your ES6 code to ES5 before minifying it.

**Comment by boanneu** [comment]
oke, tank you for helping, i use the first won i can`t ES6 or ES5 ;)
